// Mirrors backend/config/eventConfig.js so the site still renders
// sensible content if the API hasn't loaded yet (or is briefly down).
export const fallbackConfig = {
  eventName: "ROAR — Business Expo Nagpur",
  eventCity: "Nagpur",
  eventTagline: "RISE • OPPORTUNITY • AMBITION • REACH",
  eventDatesLabel: "8th to 10th January 2027",
  eventStartDateISO: "2027-01-08",
  eventEndDateISO: "2027-01-10",
  venueName: "MSB Ground, Nagpur",
  venueMapUrl: "https://www.google.com/maps/search/?api=1&query=MSB+Ground+Nagpur",
  totalStalls: "150+",
  organizers: [
    { name: "Dawoodi Bohra Department of Economic Affairs", tagline: "Nagpur Jamiyat" },
  ],
  contact: {
    whatsapp: "+91 92841 82675",
    whatsappNote: "WhatsApp Message Only — No Calls",
    email: "mkt@roarexpo.com",
  },
  registrationDeadlines: { stall: "20 December 2026", visitor: "6 January 2027" },
  stallPackages: [
    { code: "title", label: "Title Stall", icon: "🏆", rate: 1053000, size: "3m × 8m / 4m × 6m", stallCount: 2, hasStallPicker: true, inclusions: "24 sq m · Prime frontage, maximum branding exposure, premium furnishing package" },
    { code: "diamond", label: "Diamond Stall", icon: "💎", rate: 753000, size: "3m × 6m", stallCount: 2, hasStallPicker: true, inclusions: "18 sq m · Prime location, enhanced branding, premium furnishing package" },
    { code: "gold", label: "Gold Stall", icon: "🥇", rate: 553000, size: "3m × 5m", stallCount: 4, hasStallPicker: true, inclusions: "15 sq m · High-visibility location, premium furnishing package" },
    { code: "silver", label: "Silver Stall", icon: "🥈", rate: 353000, size: "3m × 4m", stallCount: 4, hasStallPicker: true, inclusions: "12 sq m · Good-visibility location, standard furnishing package" },
    { code: "bronze", label: "Bronze Stall", icon: "🥉", rate: 253000, size: "3m × 5m", stallCount: 4, hasStallPicker: true, inclusions: "15 sq m · Standard furnishing package, fascia signage" },
    { code: "premium-corner", label: "Premium Corner Stall", icon: "⭐", rate: 100000, size: "3m × 4m", stallCount: 5, hasStallPicker: true, inclusions: "12 sq m · Corner location (PP1–PP5), fascia signage" },
    { code: "premium", label: "Premium Stall", icon: "⭐", rate: 72000, size: "3m × 4m", stallCount: 19, hasStallPicker: true, inclusions: "12 sq m · 1 table, 2 chairs, power point, fascia signage" },
    { code: "premium-ruby", label: "Premium Corner Stall (9 sq m)", icon: "⭐", rate: 72000, size: "3m × 3m", stallCount: 4, hasStallPicker: true, inclusions: "9 sq m · Premium corner (PR1–PR4), fascia signage" },
    { code: "premium-corner-15", label: "Premium Stall (15 sq m)", icon: "⭐", rate: 53000, size: "3m × 5m", stallCount: 2, hasStallPicker: true, inclusions: "15 sq m · Corner location (PP6–PP7), fascia signage" },
    { code: "premium-ruby-53", label: "Premium Ruby Stall (Standard)", rate: 53000, size: "3m × 3m", stallCount: 4, hasStallPicker: true, inclusions: "9 sq m · Premium Ruby (PR5–PR8), fascia signage" },
    { code: "regular", label: "Regular Stall", rate: 53000, size: "3m × 3m", stallCount: 66, hasStallPicker: true, inclusions: "9 sq m · 1 table, 2 chairs, power point, fascia signage" },
    { code: "ruby", label: "Ruby Stall", rate: 24000, size: "3m × 3m", stallCount: 32, hasStallPicker: true, eligibility: "Available only for Women Entrepreneurs of the Dawoodi Bohra Community. RU1–RU13 can be booked online; RU14–RU32 are allotted by the organizing team.", inclusions: "9 sq m · 1 table, 2 chairs, power point, fascia signage" },
    { code: "food-court", label: "Food Court", rate: null, sizeLabel: "2,000 – 3,000 sq. ft.", hasStallPicker: false, inclusions: "Space allocation and pricing discussed directly with the organizing team" },
    { code: "play-zone", label: "Play Zone", rate: null, sizeLabel: "1,000 sq. ft.", hasStallPicker: false, inclusions: "Space allocation and pricing discussed directly with the organizing team" },
  ],
  totalStallsNumbered: 148,
  categories: [
    { key: "industrial-machinery", label: "Industrial Machinery" },
    { key: "robotics-automation", label: "Robotics & Automation" },
    { key: "manufacturing", label: "Manufacturing" },
    { key: "plywood-hardware-tools", label: "Plywood / Hardware & Tools" },
    { key: "construction-real-estate", label: "Construction & Real Estate" },
    { key: "jewellery-luxury", label: "Jewellery & Luxury" },
    { key: "it-technology", label: "IT & Technology" },
    { key: "renewable-energy-solar", label: "Renewable Energy & Solar" },
    { key: "automotive-ev", label: "Automotive & EV" },
    { key: "healthcare-medical", label: "Healthcare & Medical" },
    { key: "fmcg-consumer-goods", label: "FMCG & Consumer Goods" },
    { key: "food-beverage", label: "Food & Beverage" },
    { key: "textiles-apparel", label: "Textiles & Apparel" },
    { key: "education-skills", label: "Education & Skills" },
    { key: "electrical-electronics", label: "Electrical & Electronics" },
    { key: "travel-hospitality", label: "Travel & Hospitality" },
  ],
  exhibitorInstructions: {
    setupWindow: "6 – 7 January 2027, 10:00 AM – 8:00 PM",
    moveOutWindow: "10 January 2027, 7:00 PM – 11:00 PM",
    dailyShowTiming: "10:00 AM – 8:00 PM (all 3 days)",
  },
};
