// Mirrors backend/config/eventConfig.js so the site still renders
// sensible content if the API hasn't loaded yet (or is briefly down).
export const fallbackConfig = {
  eventName: "ROAR — Business Expo Nagpur",
  eventCity: "Nagpur",
  eventTagline: "RISE • OPPORTUNITY • AMBITION • REACH",
  eventDatesLabel: "8 – 10 January 2027",
  eventStartDateISO: "2027-01-08",
  eventEndDateISO: "2027-01-10",
  venueName: "MSB Ground, Nagpur",
  venueMapUrl: "https://www.google.com/maps/search/?api=1&query=MSB+Ground+Nagpur",
  totalStalls: "100+",
  organizers: [
    { name: "Dawoodi Bohra Department of Economic Affairs", tagline: "Nagpur Jamiyat" },
  ],
  contact: {
    whatsapp: "+91 92841 82675",
    whatsappNote: "WhatsApp Message Only — No Calls",
    email: "mkt@roarexpo.com",
  },
  registrationDeadlines: { stall: "20 December 2026", visitor: "6 January 2027" },
  stallPackages: [
    { code: "title", label: "Title Stall", icon: "🏆", rate: 2100000, stallCount: 1, hasStallPicker: true, inclusions: "Prime frontage location, maximum branding exposure, premium furnishing package" },
    { code: "diamond", label: "Diamond Stall", icon: "💎", rate: 753000, stallCount: 2, hasStallPicker: true, inclusions: "Prime location, enhanced branding, premium furnishing package" },
    { code: "gold", label: "Gold Stall", icon: "🥇", rate: 453000, stallCount: 3, hasStallPicker: true, inclusions: "High-visibility location, premium furnishing package" },
    { code: "silver", label: "Silver Stall", icon: "🥈", rate: 353000, stallCount: 4, hasStallPicker: true, inclusions: "Good-visibility location, standard furnishing package" },
    { code: "bronze", label: "Bronze Stall", icon: "🥉", rate: 153000, stallCount: 5, hasStallPicker: true, inclusions: "Standard furnishing package, fascia signage" },
    { code: "premium", label: "Premium Stall", icon: "⭐", rate: 72000, stallCount: 11, hasStallPicker: true, inclusions: "1 table, 2 chairs, power point, fascia signage" },
    { code: "regular", label: "Regular Stall", rate: 53000, stallCount: 27, hasStallPicker: true, inclusions: "1 table, 2 chairs, power point, fascia signage" },
    { code: "ruby", label: "Ruby Stall", rate: 24000, stallCount: 50, hasStallPicker: true, inclusions: "1 table, 2 chairs, power point, fascia signage" },
    { code: "food-court", label: "Food Court", rate: null, sizeLabel: "2,000 – 3,000 sq. ft.", hasStallPicker: false, inclusions: "Space allocation and pricing discussed directly with the organizing team" },
    { code: "play-zone", label: "Play Zone", rate: null, sizeLabel: "1,000 sq. ft.", hasStallPicker: false, inclusions: "Space allocation and pricing discussed directly with the organizing team" },
  ],
  totalStallsNumbered: 103,
  categories: [
    { key: "industrial-machinery", label: "Industrial Machinery" },
    { key: "robotics-automation", label: "Robotics & Automation" },
    { key: "manufacturing", label: "Manufacturing" },
    { key: "plywood-hardware-tools", label: "Plywood / Hardware & Tools" },
    { key: "construction-real-estate", label: "Construction & Real Estate" },
    { key: "jewellery-luxury", label: "Jewellery & Luxury" },
    { key: "it-technology", label: "IT & Technology" },
    { key: "renewable-energy-solar", label: "Renewable Energy & Solar" },
    { key: "automotive-ev", label: "Automotive & EV" },
    { key: "healthcare-medical", label: "Healthcare & Medical" },
    { key: "fmcg-consumer-goods", label: "FMCG & Consumer Goods" },
    { key: "food-beverage", label: "Food & Beverage" },
    { key: "textiles-apparel", label: "Textiles & Apparel" },
    { key: "education-skills", label: "Education & Skills" },
    { key: "electrical-electronics", label: "Electrical & Electronics" },
    { key: "travel-hospitality", label: "Travel & Hospitality" },
  ],
  exhibitorInstructions: {
    setupWindow: "6 – 7 January 2027, 10:00 AM – 8:00 PM",
    moveOutWindow: "10 January 2027, 7:00 PM – 11:00 PM",
    dailyShowTiming: "10:00 AM – 8:00 PM (all 3 days)",
  },
};
